use std::env;
use std::fs::{self, File};
use std::io::Write;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let repo_root = manifest_dir.join("..").canonicalize()?;

    let mut years: Vec<(String, Vec<String>)> = Vec::new();

    for entry in fs::read_dir(&repo_root)? {
        let entry = entry?;
        let p = entry.path();
        if !p.is_dir() {
            continue;
        }
        let name = match p.file_name().and_then(|s| s.to_str()) {
            Some(n) => n.to_string(),
            None => continue,
        };
        // consider directories named like years: 4 digits
        if name.len() != 4 || !name.chars().all(|c| c.is_ascii_digit()) {
            continue;
        }
        let solutions_dir = p.join("solutions");
        if !solutions_dir.exists() {
            continue;
        }
        let mut days: Vec<String> = Vec::new();
        for file in fs::read_dir(&solutions_dir)? {
            let file = file?;
            let fp = file.path();
            if fp.extension().and_then(|s| s.to_str()) != Some("rs") {
                continue;
            }
            if let Some(stem) = fp.file_stem().and_then(|s| s.to_str()) {
                days.push(stem.to_string());
            }
        }
        if !days.is_empty() {
            days.sort();
            years.push((name, days));
        }
    }

    // Generate src/generated_mods.rs
    let out_path = manifest_dir.join("src").join("generated_mods.rs");
    let mut f = File::create(&out_path)?;

    writeln!(f, "// This file is @generated by build.rs - do not edit")?;
    writeln!(f, "// Generated modules for year/day solutions")?;
    writeln!(f)?;

    // Write module declarations
    for (year, days) in &years {
        let year_mod = format!("year{}", year);
        writeln!(f, "pub mod {} {{", year_mod)?;
        for day in days {
            let mod_name = format!("day{}", day);
            writeln!(
                f,
                "    pub mod {} {{ include!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../{}/solutions/{}.rs\")); }}",
                mod_name, year, day
            )?;
        }
        writeln!(f, "}}\n")?;
    }

    // Write dispatcher
    writeln!(f, "pub fn dispatch(year: &str, day: &str, input: &str) -> Result<(), String> {{")?;
    writeln!(f, "    match (year, day) {{")?;
    for (year, days) in &years {
        let year_mod = format!("year{}", year);
        for day in days {
            writeln!(
                f,
                "        (\"{}\", \"{}\") => {{ {}::day{}::run(input); Ok(()) }},",
                year, day, year_mod, day
            )?;
        }
    }
    writeln!(f, "        _ => Err(format!(\"No compiled solution available for {{}} {{}}.\", year, day)),")?;
    writeln!(f, "    }}")?;
    writeln!(f, "}}")?;

    // Tell cargo to re-run the build script when the solutions folder changes
    println!("cargo:rerun-if-changed={}", repo_root.display());

    Ok(())
}
